channels:
- conda-forge
dependencies:
- python=3.10.8
- pip<=22.2.2
- pip:
  - mlflow==2.12.1
  - cloudpickle==3.0.0
  - numpy==1.23.5
  - packaging==23.2
  - pyyaml==6.0.1
  - scikit-learn==1.4.2
  - scipy==1.13.0
name: mlflow-env
