name: CD.yaml

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v1

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build --build-arg DB_SERVER="${{ secrets.DB_SERVER }}" --build-arg DB_DATABASE="${{ secrets.DB_DATABASE }}" --build-arg DB_USERNAME="${{ secrets.DB_USERNAME }}" --build-arg DB_PASSWORD="${{ secrets.DB_PASSWORD }}" --build-arg SECRET_KEY="${{ secrets.SECRET_KEY }}" --build-arg TOKEN="${{ secrets.TOKEN }}" -t "${{ secrets.DOCKER_LOGIN }}"/api_ia_certif .
        docker push "${{ secrets.DOCKER_LOGIN }}"/api_ia_certif

    - name: Restart Azure Container
      uses: azure/container-instance-restart@v1
      with:
        resource-group: Impe_Jonathan
        container-group: api-ia-certif
        azure-creds: ${{ secrets.AZURE_CREDENTIALS }}
