name: CD_azure

on:
  push:
    branches: [ dev ]

jobs:
  restart_azure_container:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Restart Azure Container Instance
      run: |
        az container restart --resource-group Impe_Jonathan --name api-ia-certif --subscription 111aaa69-41b9-4dfd-b6af-2ada039dd1ae
