name: CD_azure

on:
  push:
    branches: [ dev ]

jobs:
  build_CD_azure:

    runs-on: ubuntu-latest

    steps:
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Restart ACI container'
      run: |
        az group deployment delete --name myDeployment --resource-group myResourceGroup
        az group deployment create --name myDeployment --resource-group myResourceGroup --template-file ./template.json --parameters parameter1=value1 parameter2=value2
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
