name: CD_azure

on:
  push:
    branches: [ dev ]

jobs:
  build_CD_azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Restart Azure container
      uses: azure/CLI@v2
      with:
        azcliversion: 2.0.80
        inlineScript: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az container restart --name api-ia-certif --resource-group Impe_Jonathan

    - name: Logout of Azure
      run: az logout
