name: CD_azure

on:
  push:
    branches: [ dev ]

jobs:
  build_CD_azure:
    runs-on: ubuntu-latest
    steps:
      - name: Authentification Azure
        uses: actions/setup-azure-auth@v3
        with:
          azure-login: true
          credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Redémarrage du conteneur Azure
        run: |
          az container group restart \
            --resource-group Impe_Jonathan \
            --name api-ia-certif \
            --location FranceCentral
