name: CD_azure

on:
  push:
    branches: [ dev ]

jobs:
  build_CD_azure:

    runs-on: ubuntu-latest

    steps:
    - name: 'Set up environment'
      run: |
        echo "ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL" >> $GITHUB_ENV
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Restart ACI container'
      run: |
        az container restart --name api-ia-certif --resource-group Impe_Jonathan
