name: CI

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r projet/requirements.txt
      continue-on-error: true


    - name: Test with pytest
      run: |
        cd projet/api/tests
        pytest test_quality_api.py
      continue-on-error: true
